### ISSUE TITLE
404 error with Influxdb-python 1.0 and Influxdb 0.8.8

### ISSUE THREAD

**Issue by nicolargo** [influxdb/influxdb-python#138] opened 2015-03-27 20:55 UTC
I have a database called 'glances' on my Influxdb server:

```
$ influxdb-cli -d glances
glances> Connecting to http://localhost:8086/db/glances ...
glances> ✔ ready
glances> list series
┌──────┬────────────────────────┐
│ time │ name                   │
├──────┼────────────────────────┤
│ 0    │ cpu                    │
│ 0    │ diskio                 │
│ 0    │ fs                     │
│ 0    │ load                   │
│ 0    │ localhost.cpu          │
│ 0    │ localhost.diskio       │
│ 0    │ localhost.fs           │
│ 0    │ localhost.load         │
│ 0    │ localhost.mem          │
│ 0    │ localhost.memswap      │
│ 0    │ localhost.network      │
│ 0    │ localhost.processcount │
│ 0    │ mem                    │
│ 0    │ memswap                │
│ 0    │ network                │
│ 0    │ processcount           │
└──────┴────────────────────────┘
Query took  5 ms
```

But i raise a 404 error if i try to use Influxdb-python 1.0:

```
$ ipython
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 

In [1]: import influxdb

In [2]: influxdb.__version__
Out[2]: '1.0.0'

In [3]: influxdb.InfluxDBClient(database='glances').get_list_database()
---------------------------------------------------------------------------
InfluxDBClientError                       Traceback (most recent call last)
<ipython-input-3-16de30d78c8d> in <module>()
----> 1 influxdb.InfluxDBClient(database='glances').get_list_database()

/usr/local/lib/python2.7/dist-packages/influxdb/client.pyc in get_list_database(self)
    297         Get the list of databases
    298         """
--> 299         return [db['name'] for db in self.query("SHOW DATABASES")]
    300 
    301     def create_database(self, dbname):

/usr/local/lib/python2.7/dist-packages/influxdb/client.pyc in query(self, query, params, expected_response_code, database, raw)
    225             params=params,
    226             data=None,
--> 227             expected_response_code=expected_response_code
    228         )
    229 

/usr/local/lib/python2.7/dist-packages/influxdb/client.pyc in request(self, url, method, params, data, expected_response_code)
    189             return response
    190         else:
--> 191             raise InfluxDBClientError(response.content, response.status_code)
    192 
    193     def write(self, data, params=None, expected_response_code=200):

InfluxDBClientError: 404: 404 page not found

```

Any idea ?

**Comment by ReAzem** [comment] 2015-03-27 20:59
What version of InfluxDB are you using?

The [README](https://github.com/influxdb/influxdb-python/blob/master/README.rst) should fix your problem. It looks like you are using InfluxDB 0.8 with the wrong InfluxDBClient. If you are using InfluxDB 0.8, you should use ``influxdb.influxdb08.InfluxDBClient``.

That would be a duplicate of #135 and #137

**Comment by nicolargo** [comment] 2015-03-27 21:04
Exact ! I use the version 0.8.8...

Sorry !

**Comment by nicolargo** [comment] 2015-03-27 21:15
Sorry, but can find influxdb08:

```
...

In [3]: influxdb.__version__
Out[3]: '1.0.0'

In [4]: influxdb.
influxdb.DataFrameClient   influxdb.SeriesHelper      influxdb.dataframe_client  
influxdb.InfluxDBClient    influxdb.client            influxdb.helper  
```

**Closed** 2015-03-27 21:15 UTC
