### ISSUE TITLE
Writting NaN values makes the Client to fail

### ISSUE THREAD

**Issue by svernede** [influxdb/influxdb-python#195] opened 2015-06-15 05:29 UTC
Writting a `NaN` value makes the Client to fail. Only tested with influxdb08 

with the DataFrameClient

```
import pandas as pd
from influxdb.influxdb08  import DataFrameClient
data = pd.DataFrame({
            'value':[1.5,float('Nan'),3.2]},
             index=pd.date_range('01-01-2015', periods=3, freq='D'))

client = DataFrameClient(host, port, user, password, dbname)

client.write_points({'test':data})
```
raises the error

```
<class \'influxdb.influxdb08.client.InfluxDBClientError\'> : 400: b"invalid character \'N\' looking for beginning of value"
```

The client tries to write the value `NaN` which is not a valid JSON value. Python `NaN` should be mapped to JSON `null`. This is coherent with the Pandas usage to encode missing data by `NaN`

**Comment by aviau** [comment] 2015-07-05 14:15
Fixed in #204

**Closed by aviau** 2015-07-05 14:15 UTC

**Comment by julienvienne** [comment] 2016-01-18 09:16
Hello,
Is this code tested in the last version ?
Some numpy NaN don't seems to be understood in the last revision :

Best regards,

Traceback (most recent call last):
  File "/home/julienv/weatherdata/weatherdata/acquisition/observation/weenat/WeenatInflux.py", line 45, in <module>
    influx_connexion.write_points(df_wmo, 'synop', {'wmo': wmo})
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/_dataframe_client.py", line 68, in write_points
    points, time_precision, database, retention_policy)
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/client.py", line 391, in write_points
    tags=tags)
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/client.py", line 436, in _write_points
    expected_response_code=204
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/client.py", line 278, in write
    headers=headers
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/client.py", line 248, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write:\nunable to parse 'synop,wmo=7002 tp01h=0i,tp03h=nan 1420570800000000000': invalid number\nunable to parse 'synop,wmo=7002 tp01h=0i,tp03h=nan 1420574400000000000': invalid number\nunable to parse 'synop,wmo=7002 tp01h=0i,tp03h=nan 1420581600000000000': invalid number\nunable to parse 'synop,wmo=7002 tp01h=0i,tp03h=nan 1420585200000000000': invalid number"}

**Comment by julienvienne** [comment] 2016-01-18 10:04
Hello, 
Here is a simple code in order to reproduce the bug :
Test data : [nan_data_test.zip](https://github.com/influxdata/influxdb-python/files/94065/nan_data_test.zip)
```
from influxdb import DataFrameClient
import pandas as pd

host='server1'
port = 8086
user = 'root'
password = 'root'
dbname = 'weather_test'

influx_connexion = DataFrameClient(host, port, user, password, dbname)
print("Delete database: " + dbname)
influx_connexion.drop_database(dbname)

print("Create database: " + dbname)
influx_connexion.create_database(dbname)

# This insertion is OK (uncomment to test)
#df_nonan = pd.read_csv("data_test_no_na.csv", sep=";", header=False,  index_col=[0], #parse_dates=True, na_values="")
#influx_connexion.write_points(df_nonan, 'weather', {'station_code': '07002'})

# This insertion with NAN fails
df_withnan = pd.read_csv("data_test_with_na.csv", sep=";", header=False,  index_col=[0], parse_dates=True, na_values="")
influx_connexion.write_points(df_withnan, 'weather', {'station_code': '07002'})


# Traceback :
Traceback (most recent call last):
  File "/home/julienv/weatherdata/weatherdata/acquisition/observation/weenat/test_nan.py", line 25, in <module>
    influx_connexion.write_points(df_withnan, 'weather', {'station_code': '07002'})
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/_dataframe_client.py", line 68, in write_points
    points, time_precision, database, retention_policy)
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/client.py", line 391, in write_points
    tags=tags)
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/client.py", line 436, in _write_points
    expected_response_code=204
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/client.py", line 278, in write
    headers=headers
  File "/usr/local/lib/python3.4/dist-packages/influxdb-2.11.0-py3.4.egg/influxdb/client.py", line 248, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write:\nunable to parse 'weather,station_code=07002 td=3.2,tp01h=nan 1420092000000000000': invalid number\nunable to parse 'weather,station_code=07002 td=nan,tp01h=0.0 1420113600000000000': invalid number"}
```

**Comment by julienvienne** [comment] 2016-01-18 15:03
I found a workaround that may be used : replace numpy.nan by None before inserting data:
```
df_withnan = df_withnan.where((pd.notnull(df_withnan)), None)
```
Best regards

**Comment by t-pfaff** [comment] 2017-02-07 16:36
@julienvienne: Downside is that the conversion to None changes the type to Object. If you have a field in InfluxDB which already has, e.g., float values, and you then insert new data with NaNs, the conversion to None changes the type and InfluxDB throws an error.

For example: 

`InfluxDBClientError: 400: {"error":"field type conflict: input field \"kas_AnlMenge\" on measurement \"artikel_tuning\" is type string, already exists as type float"}`

@aviau: Maybe you want to open the issue again?

**Comment by shagru** [comment] 2017-03-07 02:30
I've encountered the same error in the latest version. The issue lies in "synop,wmo=7002 tp01h=0i,tp03h=nan 1420585200000000000" where "tp03h=nan" cannot be interpreted by influxdb line protocol. The best solution might be just to omit the nan value field in the line protocol input, like "synop,wmo=7002 tp01h=0i 1420585200000000000". This way, influxdb will put an empty value in that field. Also, we might need to check for "inf" as well since influxdb seems to not support that either. So, maybe we need to check for "np.isfinite()" and omit the value field that is not finite in the line protocol input.

**Comment by acezzz** [comment] 2018-02-03 08:00
I have encountered the same error in version 5.0.0. The workaround julienvienne provided does not work as well.
