### ISSUE TITLE
database creation name encoding problems

### ISSUE THREAD

**Issue by robbyt** [influxdb/influxdb-python#111] opened 2015-03-04 00:44 UTC
I'm testing the v0.90 branch, and I get the following error when I create a db with characters like `-` or `|`.

```python
influxdb_client.create_database("not-valid")

InfluxDBClientError('400: {"error":"error parsing query: found -, expected ;, EOF at line 1, char 23"}',)
```

**Comment by ReAzem** [comment] 2015-03-04 01:20
Tank you for testing the client! 

I could not make it work, even with the influx shell. Quoting the series name created a database named ```"not-valid"``` (with the quoted in the name). Using single quotes didn't work ethier. Escaping the quotes didn't help.

This might be a bug in InfluxDB.

@otoolep Any idea? What should the command look like?

**Comment by ReAzem** [comment] 2015-03-04 01:23
Looks like its a bug in InfluxDB. See influxdb/influxdb#1194

**Comment by ReAzem** [comment] 2015-03-19 14:54
As this is reproductible with the influx shell, I will close this. This should be opened in the InfluxDB repo.

**Closed by ReAzem** 2015-03-19 14:54 UTC
